/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TrialId = IDL.Nat;
export const EnrollmentId = IDL.Nat;
export const EnrollmentError = IDL.Variant({
  'ok' : EnrollmentId,
  'unknownTrial' : TrialId,
  'alreadyEnrolled' : TrialId,
  'notEnrolled' : EnrollmentId,
  'notSignedIn' : IDL.Null,
  'invalidProgress' : IDL.Nat,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const StudentProfile = IDL.Record({ 'displayName' : IDL.Text });
export const AspectScore = IDL.Record({
  'aspect' : IDL.Text,
  'score' : IDL.Nat,
});
export const EvidenceId = IDL.Nat;
export const TestResult = IDL.Record({
  'trialId' : TrialId,
  'trialName' : IDL.Text,
  'score' : IDL.Nat,
  'completionPercent' : IDL.Nat,
  'aspectScores' : IDL.Vec(AspectScore),
  'evidenceId' : EvidenceId,
});
export const TaskBrief = IDL.Record({
  'description' : IDL.Text,
  'deliverables' : IDL.Vec(IDL.Text),
  'checklist' : IDL.Vec(IDL.Text),
});
export const CareerTrial = IDL.Record({
  'id' : TrialId,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'daysToComplete' : IDL.Nat,
  'summary' : IDL.Text,
  'brief' : TaskBrief,
});
export const TestOption = IDL.Record({ 'id' : IDL.Nat, 'text' : IDL.Text });
export const TestQuestionView = IDL.Record({
  'id' : IDL.Nat,
  'aspect' : IDL.Text,
  'prompt' : IDL.Text,
  'options' : IDL.Vec(TestOption),
});
export const TrialTestView = IDL.Record({
  'trialId' : TrialId,
  'trialName' : IDL.Text,
  'questions' : IDL.Vec(TestQuestionView),
});
export const EvidenceCard = IDL.Record({
  'id' : EvidenceId,
  'testerName' : IDL.Text,
  'trialName' : IDL.Text,
  'completionPercent' : IDL.Nat,
  'aspectScores' : IDL.Vec(AspectScore),
  'rating' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const EnrollmentView = IDL.Record({
  'id' : EnrollmentId,
  'startedAt' : Timestamp,
  'trialId' : TrialId,
  'trialName' : IDL.Text,
  'updatedAt' : Timestamp,
  'progressPercent' : IDL.Nat,
});
export const MyEvidenceCard = IDL.Record({
  'id' : EvidenceId,
  'trialId' : TrialId,
  'trialName' : IDL.Text,
  'completionPercent' : IDL.Nat,
  'aspectScores' : IDL.Vec(AspectScore),
  'rating' : IDL.Nat,
});
export const ProfileError = IDL.Variant({
  'ok' : IDL.Null,
  'invalidName' : IDL.Null,
  'notSignedIn' : IDL.Null,
});
export const TestAnswer = IDL.Record({
  'optionId' : IDL.Nat,
  'questionId' : IDL.Nat,
});
export const TestError = IDL.Variant({
  'ok' : TestResult,
  'incomplete' : IDL.Vec(IDL.Nat),
  'unknownTrial' : TrialId,
  'notEnrolled' : TrialId,
  'invalidAnswer' : IDL.Nat,
  'notSignedIn' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'enroll' : IDL.Func([TrialId], [EnrollmentError], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
  'getMyTestResult' : IDL.Func([TrialId], [IDL.Opt(TestResult)], ['query']),
  'getTrial' : IDL.Func([TrialId], [IDL.Opt(CareerTrial)], ['query']),
  'getTrialTest' : IDL.Func([TrialId], [IDL.Opt(TrialTestView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listEvidence' : IDL.Func([], [IDL.Vec(EvidenceCard)], ['query']),
  'listMyEnrollments' : IDL.Func([], [IDL.Vec(EnrollmentView)], ['query']),
  'listMyEvidence' : IDL.Func([], [IDL.Vec(MyEvidenceCard)], ['query']),
  'listTrials' : IDL.Func([], [IDL.Vec(CareerTrial)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'setMyDisplayName' : IDL.Func([IDL.Text], [ProfileError], []),
  'submitTest' : IDL.Func([TrialId, IDL.Vec(TestAnswer)], [TestError], []),
  'updateProgress' : IDL.Func([EnrollmentId, IDL.Nat], [EnrollmentError], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TrialId = IDL.Nat;
  const EnrollmentId = IDL.Nat;
  const EnrollmentError = IDL.Variant({
    'ok' : EnrollmentId,
    'unknownTrial' : TrialId,
    'alreadyEnrolled' : TrialId,
    'notEnrolled' : EnrollmentId,
    'notSignedIn' : IDL.Null,
    'invalidProgress' : IDL.Nat,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const StudentProfile = IDL.Record({ 'displayName' : IDL.Text });
  const AspectScore = IDL.Record({ 'aspect' : IDL.Text, 'score' : IDL.Nat });
  const EvidenceId = IDL.Nat;
  const TestResult = IDL.Record({
    'trialId' : TrialId,
    'trialName' : IDL.Text,
    'score' : IDL.Nat,
    'completionPercent' : IDL.Nat,
    'aspectScores' : IDL.Vec(AspectScore),
    'evidenceId' : EvidenceId,
  });
  const TaskBrief = IDL.Record({
    'description' : IDL.Text,
    'deliverables' : IDL.Vec(IDL.Text),
    'checklist' : IDL.Vec(IDL.Text),
  });
  const CareerTrial = IDL.Record({
    'id' : TrialId,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'daysToComplete' : IDL.Nat,
    'summary' : IDL.Text,
    'brief' : TaskBrief,
  });
  const TestOption = IDL.Record({ 'id' : IDL.Nat, 'text' : IDL.Text });
  const TestQuestionView = IDL.Record({
    'id' : IDL.Nat,
    'aspect' : IDL.Text,
    'prompt' : IDL.Text,
    'options' : IDL.Vec(TestOption),
  });
  const TrialTestView = IDL.Record({
    'trialId' : TrialId,
    'trialName' : IDL.Text,
    'questions' : IDL.Vec(TestQuestionView),
  });
  const EvidenceCard = IDL.Record({
    'id' : EvidenceId,
    'testerName' : IDL.Text,
    'trialName' : IDL.Text,
    'completionPercent' : IDL.Nat,
    'aspectScores' : IDL.Vec(AspectScore),
    'rating' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const EnrollmentView = IDL.Record({
    'id' : EnrollmentId,
    'startedAt' : Timestamp,
    'trialId' : TrialId,
    'trialName' : IDL.Text,
    'updatedAt' : Timestamp,
    'progressPercent' : IDL.Nat,
  });
  const MyEvidenceCard = IDL.Record({
    'id' : EvidenceId,
    'trialId' : TrialId,
    'trialName' : IDL.Text,
    'completionPercent' : IDL.Nat,
    'aspectScores' : IDL.Vec(AspectScore),
    'rating' : IDL.Nat,
  });
  const ProfileError = IDL.Variant({
    'ok' : IDL.Null,
    'invalidName' : IDL.Null,
    'notSignedIn' : IDL.Null,
  });
  const TestAnswer = IDL.Record({
    'optionId' : IDL.Nat,
    'questionId' : IDL.Nat,
  });
  const TestError = IDL.Variant({
    'ok' : TestResult,
    'incomplete' : IDL.Vec(IDL.Nat),
    'unknownTrial' : TrialId,
    'notEnrolled' : TrialId,
    'invalidAnswer' : IDL.Nat,
    'notSignedIn' : IDL.Null,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'enroll' : IDL.Func([TrialId], [EnrollmentError], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
    'getMyTestResult' : IDL.Func([TrialId], [IDL.Opt(TestResult)], ['query']),
    'getTrial' : IDL.Func([TrialId], [IDL.Opt(CareerTrial)], ['query']),
    'getTrialTest' : IDL.Func([TrialId], [IDL.Opt(TrialTestView)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listEvidence' : IDL.Func([], [IDL.Vec(EvidenceCard)], ['query']),
    'listMyEnrollments' : IDL.Func([], [IDL.Vec(EnrollmentView)], ['query']),
    'listMyEvidence' : IDL.Func([], [IDL.Vec(MyEvidenceCard)], ['query']),
    'listTrials' : IDL.Func([], [IDL.Vec(CareerTrial)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'setMyDisplayName' : IDL.Func([IDL.Text], [ProfileError], []),
    'submitTest' : IDL.Func([TrialId, IDL.Vec(TestAnswer)], [TestError], []),
    'updateProgress' : IDL.Func([EnrollmentId, IDL.Nat], [EnrollmentError], []),
  });
};

export const init = ({ IDL }) => { return []; };