/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AspectScore { 'aspect' : string, 'score' : bigint }
export interface CareerTrial {
  'id' : TrialId,
  'name' : string,
  'tags' : Array<string>,
  'daysToComplete' : bigint,
  'summary' : string,
  'brief' : TaskBrief,
}
export interface Cell { 'value' : Value, 'name' : string }
export type EnrollmentError = { 'ok' : EnrollmentId } |
  { 'unknownTrial' : TrialId } |
  { 'alreadyEnrolled' : TrialId } |
  { 'notEnrolled' : EnrollmentId } |
  { 'notSignedIn' : null } |
  { 'invalidProgress' : bigint };
export type EnrollmentId = bigint;
export interface EnrollmentView {
  'id' : EnrollmentId,
  'startedAt' : Timestamp,
  'trialId' : TrialId,
  'trialName' : string,
  'updatedAt' : Timestamp,
  'progressPercent' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface EvidenceCard {
  'id' : EvidenceId,
  'testerName' : string,
  'trialName' : string,
  'completionPercent' : bigint,
  'aspectScores' : Array<AspectScore>,
  'rating' : bigint,
}
export type EvidenceId = bigint;
export interface MyEvidenceCard {
  'id' : EvidenceId,
  'trialId' : TrialId,
  'trialName' : string,
  'completionPercent' : bigint,
  'aspectScores' : Array<AspectScore>,
  'rating' : bigint,
}
export type ProfileError = { 'ok' : null } |
  { 'invalidName' : null } |
  { 'notSignedIn' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface StudentProfile { 'displayName' : string }
export interface TaskBrief {
  'description' : string,
  'deliverables' : Array<string>,
  'checklist' : Array<string>,
}
export interface TestAnswer { 'optionId' : bigint, 'questionId' : bigint }
export type TestError = { 'ok' : TestResult } |
  { 'incomplete' : Array<bigint> } |
  { 'unknownTrial' : TrialId } |
  { 'notEnrolled' : TrialId } |
  { 'invalidAnswer' : bigint } |
  { 'notSignedIn' : null };
export interface TestOption { 'id' : bigint, 'text' : string }
export interface TestQuestionView {
  'id' : bigint,
  'aspect' : string,
  'prompt' : string,
  'options' : Array<TestOption>,
}
export interface TestResult {
  'trialId' : TrialId,
  'trialName' : string,
  'score' : bigint,
  'completionPercent' : bigint,
  'aspectScores' : Array<AspectScore>,
  'evidenceId' : EvidenceId,
}
export type Timestamp = bigint;
export type TrialId = bigint;
export interface TrialTestView {
  'trialId' : TrialId,
  'trialName' : string,
  'questions' : Array<TestQuestionView>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Enrol the caller in a career trial.
   */
  'enroll' : ActorMethod<[TrialId], EnrollmentError>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Static Markdown documentation of this backend's public API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / The caller's stored display name, or null when unset.
   */
  'getMyProfile' : ActorMethod<[], [] | [StudentProfile]>,
  /**
   * / The caller's own stored test result for a trial, or null when untested.
   */
  'getMyTestResult' : ActorMethod<[TrialId], [] | [TestResult]>,
  /**
   * / One career trial by id.
   */
  'getTrial' : ActorMethod<[TrialId], [] | [CareerTrial]>,
  /**
   * / A trial's knowledge test, without the correct answers.
   */
  'getTrialTest' : ActorMethod<[TrialId], [] | [TrialTestView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Public evidence cards.
   */
  'listEvidence' : ActorMethod<[], Array<EvidenceCard>>,
  /**
   * / The caller's own enrolments.
   */
  'listMyEnrollments' : ActorMethod<[], Array<EnrollmentView>>,
  /**
   * / The caller's own evidence cards.
   */
  'listMyEvidence' : ActorMethod<[], Array<MyEvidenceCard>>,
  /**
   * / Public career trial catalogue.
   */
  'listTrials' : ActorMethod<[], Array<CareerTrial>>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Store the caller's display name, used as `testerName` on published cards.
   */
  'setMyDisplayName' : ActorMethod<[string], ProfileError>,
  /**
   * / Submit a test attempt; the backend scores it and publishes an evidence card.
   */
  'submitTest' : ActorMethod<[TrialId, Array<TestAnswer>], TestError>,
  /**
   * / Update the caller's own enrolment progress.
   */
  'updateProgress' : ActorMethod<[EnrollmentId, bigint], EnrollmentError>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];