/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface AspectScore {
    aspect: string;
    score: bigint;
}
export interface CareerTrial {
    id: TrialId;
    name: string;
    tags: Array<string>;
    daysToComplete: bigint;
    summary: string;
    brief: TaskBrief;
}
export interface Cell {
    value: Value;
    name: string;
}
export type EnrollmentError = {
    __kind__: "ok";
    ok: EnrollmentId;
} | {
    __kind__: "unknownTrial";
    unknownTrial: TrialId;
} | {
    __kind__: "alreadyEnrolled";
    alreadyEnrolled: TrialId;
} | {
    __kind__: "notEnrolled";
    notEnrolled: EnrollmentId;
} | {
    __kind__: "notSignedIn";
    notSignedIn: null;
} | {
    __kind__: "invalidProgress";
    invalidProgress: bigint;
};
export type EnrollmentId = bigint;
export interface EnrollmentView {
    id: EnrollmentId;
    startedAt: Timestamp;
    trialId: TrialId;
    trialName: string;
    updatedAt: Timestamp;
    progressPercent: bigint;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface EvidenceCard {
    id: EvidenceId;
    testerName: string;
    trialName: string;
    completionPercent: bigint;
    aspectScores: Array<AspectScore>;
    rating: bigint;
}
export type EvidenceId = bigint;
export interface MyEvidenceCard {
    id: EvidenceId;
    trialId: TrialId;
    trialName: string;
    completionPercent: bigint;
    aspectScores: Array<AspectScore>;
    rating: bigint;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface StudentProfile {
    displayName: string;
}
export interface TaskBrief {
    description: string;
    deliverables: Array<string>;
    checklist: Array<string>;
}
export interface TestAnswer {
    optionId: bigint;
    questionId: bigint;
}
export type TestError = {
    __kind__: "ok";
    ok: TestResult;
} | {
    __kind__: "incomplete";
    incomplete: Array<bigint>;
} | {
    __kind__: "unknownTrial";
    unknownTrial: TrialId;
} | {
    __kind__: "notEnrolled";
    notEnrolled: TrialId;
} | {
    __kind__: "invalidAnswer";
    invalidAnswer: bigint;
} | {
    __kind__: "notSignedIn";
    notSignedIn: null;
};
export interface TestOption {
    id: bigint;
    text: string;
}
export interface TestQuestionView {
    id: bigint;
    aspect: string;
    prompt: string;
    options: Array<TestOption>;
}
export interface TestResult {
    trialId: TrialId;
    trialName: string;
    score: bigint;
    completionPercent: bigint;
    aspectScores: Array<AspectScore>;
    evidenceId: EvidenceId;
}
export type Timestamp = bigint;
export type TrialId = bigint;
export interface TrialTestView {
    trialId: TrialId;
    trialName: string;
    questions: Array<TestQuestionView>;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum ProfileError {
    ok = "ok",
    invalidName = "invalidName",
    notSignedIn = "notSignedIn"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Enrol the caller in a career trial.
     */
    enroll(trialId: TrialId): Promise<EnrollmentError>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Static Markdown documentation of this backend's public API.
     */
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / The caller's stored display name, or null when unset.
     */
    getMyProfile(): Promise<StudentProfile | null>;
    /**
     * / The caller's own stored test result for a trial, or null when untested.
     */
    getMyTestResult(trialId: TrialId): Promise<TestResult | null>;
    /**
     * / One career trial by id.
     */
    getTrial(id: TrialId): Promise<CareerTrial | null>;
    /**
     * / A trial's knowledge test, without the correct answers.
     */
    getTrialTest(trialId: TrialId): Promise<TrialTestView | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Public evidence cards.
     */
    listEvidence(): Promise<Array<EvidenceCard>>;
    /**
     * / The caller's own enrolments.
     */
    listMyEnrollments(): Promise<Array<EnrollmentView>>;
    /**
     * / The caller's own evidence cards.
     */
    listMyEvidence(): Promise<Array<MyEvidenceCard>>;
    /**
     * / Public career trial catalogue.
     */
    listTrials(): Promise<Array<CareerTrial>>;
    schema(): Promise<string>;
    /**
     * / Store the caller's display name, used as `testerName` on published cards.
     */
    setMyDisplayName(displayName: string): Promise<ProfileError>;
    /**
     * / Submit a test attempt; the backend scores it and publishes an evidence card.
     */
    submitTest(trialId: TrialId, answers: Array<TestAnswer>): Promise<TestError>;
    /**
     * / Update the caller's own enrolment progress.
     */
    updateProgress(enrollmentId: EnrollmentId, progressPercent: bigint): Promise<EnrollmentError>;
}
import type { CareerTrial as _CareerTrial, Cell as _Cell, EnrollmentError as _EnrollmentError, EnrollmentId as _EnrollmentId, Error as _Error, ProfileError as _ProfileError, Result as _Result, Result__1 as _Result__1, StudentProfile as _StudentProfile, TestError as _TestError, TestResult as _TestResult, TrialId as _TrialId, TrialTestView as _TrialTestView, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async enroll(arg0: TrialId): Promise<EnrollmentError> {
        if (this.processError) {
            try {
                const result = await this.actor.enroll(arg0);
                return from_candid_EnrollmentError_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enroll(arg0);
            return from_candid_EnrollmentError_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<StudentProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTestResult(arg0: TrialId): Promise<TestResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTestResult(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTestResult(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrial(arg0: TrialId): Promise<CareerTrial | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrial(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrial(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrialTest(arg0: TrialId): Promise<TrialTestView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrialTest(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrialTest(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listEvidence(): Promise<Array<EvidenceCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEvidence();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEvidence();
            return result;
        }
    }
    async listMyEnrollments(): Promise<Array<EnrollmentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyEnrollments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyEnrollments();
            return result;
        }
    }
    async listMyEvidence(): Promise<Array<MyEvidenceCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyEvidence();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyEvidence();
            return result;
        }
    }
    async listTrials(): Promise<Array<CareerTrial>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTrials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTrials();
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async setMyDisplayName(arg0: string): Promise<ProfileError> {
        if (this.processError) {
            try {
                const result = await this.actor.setMyDisplayName(arg0);
                return from_candid_ProfileError_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMyDisplayName(arg0);
            return from_candid_ProfileError_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitTest(arg0: TrialId, arg1: Array<TestAnswer>): Promise<TestError> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTest(arg0, arg1);
                return from_candid_TestError_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTest(arg0, arg1);
            return from_candid_TestError_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProgress(arg0: EnrollmentId, arg1: bigint): Promise<EnrollmentError> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProgress(arg0, arg1);
                return from_candid_EnrollmentError_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProgress(arg0, arg1);
            return from_candid_EnrollmentError_n6(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Cell_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_EnrollmentError_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EnrollmentError): EnrollmentError {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_ProfileError_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfileError): ProfileError {
    return "ok" in value ? ProfileError.ok : "invalidName" in value ? ProfileError.invalidName : "notSignedIn" in value ? ProfileError.notSignedIn : value;
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TestError_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestError): TestError {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentProfile]): StudentProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TestResult]): TestResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CareerTrial]): CareerTrial | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TrialTestView]): TrialTestView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n14(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n10(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TestResult;
} | {
    incomplete: Array<bigint>;
} | {
    unknownTrial: _TrialId;
} | {
    notEnrolled: _TrialId;
} | {
    invalidAnswer: bigint;
} | {
    notSignedIn: null;
}): {
    __kind__: "ok";
    ok: TestResult;
} | {
    __kind__: "incomplete";
    incomplete: Array<bigint>;
} | {
    __kind__: "unknownTrial";
    unknownTrial: TrialId;
} | {
    __kind__: "notEnrolled";
    notEnrolled: TrialId;
} | {
    __kind__: "invalidAnswer";
    invalidAnswer: bigint;
} | {
    __kind__: "notSignedIn";
    notSignedIn: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "incomplete" in value ? {
        __kind__: "incomplete",
        incomplete: value.incomplete
    } : "unknownTrial" in value ? {
        __kind__: "unknownTrial",
        unknownTrial: value.unknownTrial
    } : "notEnrolled" in value ? {
        __kind__: "notEnrolled",
        notEnrolled: value.notEnrolled
    } : "invalidAnswer" in value ? {
        __kind__: "invalidAnswer",
        invalidAnswer: value.invalidAnswer
    } : "notSignedIn" in value ? {
        __kind__: "notSignedIn",
        notSignedIn: value.notSignedIn
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _EnrollmentId;
} | {
    unknownTrial: _TrialId;
} | {
    alreadyEnrolled: _TrialId;
} | {
    notEnrolled: _EnrollmentId;
} | {
    notSignedIn: null;
} | {
    invalidProgress: bigint;
}): {
    __kind__: "ok";
    ok: EnrollmentId;
} | {
    __kind__: "unknownTrial";
    unknownTrial: TrialId;
} | {
    __kind__: "alreadyEnrolled";
    alreadyEnrolled: TrialId;
} | {
    __kind__: "notEnrolled";
    notEnrolled: EnrollmentId;
} | {
    __kind__: "notSignedIn";
    notSignedIn: null;
} | {
    __kind__: "invalidProgress";
    invalidProgress: bigint;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "unknownTrial" in value ? {
        __kind__: "unknownTrial",
        unknownTrial: value.unknownTrial
    } : "alreadyEnrolled" in value ? {
        __kind__: "alreadyEnrolled",
        alreadyEnrolled: value.alreadyEnrolled
    } : "notEnrolled" in value ? {
        __kind__: "notEnrolled",
        notEnrolled: value.notEnrolled
    } : "notSignedIn" in value ? {
        __kind__: "notSignedIn",
        notSignedIn: value.notSignedIn
    } : "invalidProgress" in value ? {
        __kind__: "invalidProgress",
        invalidProgress: value.invalidProgress
    } : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n12(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
